from __future__ import annotations

import pytest


@pytest.fixture(autouse=True)
def isolate_runtime_env(tmp_path, monkeypatch: pytest.MonkeyPatch) -> None:
    agent_home = tmp_path / ".teambot" / "agents" / "test-agent"
    monkeypatch.setenv("AGENT_HOME", str(agent_home))
    monkeypatch.delenv("WORKING_DIR", raising=False)
    monkeypatch.delenv("ACTIVE_SKILLS_DIR", raising=False)
    monkeypatch.delenv("CUSTOMIZED_SKILLS_DIR", raising=False)
    monkeypatch.delenv("SKILLS_DIR", raising=False)
    monkeypatch.delenv("AGENT_MODEL", raising=False)
    monkeypatch.delenv("AGENT_PROVIDER", raising=False)
    monkeypatch.delenv("AGENT_API_KEY", raising=False)
    monkeypatch.delenv("AGENT_BASE_URL", raising=False)
    monkeypatch.delenv("AGENT_TIMEOUT_SECONDS", raising=False)
    monkeypatch.delenv("AGENT_MAX_ATTEMPTS", raising=False)
    monkeypatch.delenv("AGENT_FALLBACKS_JSON", raising=False)
    monkeypatch.delenv("SUMMARY_MODEL", raising=False)
    monkeypatch.delenv("SUMMARY_PROVIDER", raising=False)
    monkeypatch.delenv("SUMMARY_API_KEY", raising=False)
    monkeypatch.delenv("SUMMARY_BASE_URL", raising=False)
    monkeypatch.delenv("SUMMARY_TIMEOUT_SECONDS", raising=False)
    monkeypatch.delenv("SUMMARY_MAX_ATTEMPTS", raising=False)
    monkeypatch.delenv("SUMMARY_FALLBACKS_JSON", raising=False)
    monkeypatch.delenv("MODEL_DEFINITIONS_JSON", raising=False)
    monkeypatch.delenv("MODEL_PROFILE_BINDINGS_JSON", raising=False)
    monkeypatch.delenv("MODEL_DEFINITIONS_FILE", raising=False)
    monkeypatch.delenv("MODEL_PROFILE_BINDINGS_FILE", raising=False)
    monkeypatch.delenv("MODEL_PROFILES_JSON", raising=False)
    monkeypatch.delenv("RUNTIME_CONFIG_FILE", raising=False)
    monkeypatch.delenv("ALLOW_HIGH_RISK_ACTIONS", raising=False)
    monkeypatch.delenv("HIGH_RISK_ALLOWED_ACTIONS", raising=False)
    monkeypatch.delenv("TOOLS_PROFILE", raising=False)
    monkeypatch.delenv("TOOLS_NAMESAKE_STRATEGY", raising=False)
    monkeypatch.delenv("ENABLE_DESKTOP_SCREENSHOT_TOOL", raising=False)
    monkeypatch.delenv("ENABLE_SEND_FILE_TOOL", raising=False)
    monkeypatch.delenv("ENABLE_ECHO_TOOL", raising=False)
    monkeypatch.delenv("ENABLE_EXEC_TOOL", raising=False)
    monkeypatch.delenv("EXEC_TIMEOUT_SECONDS", raising=False)
    monkeypatch.delenv("BROWSER_TIMEOUT_SECONDS", raising=False)
    monkeypatch.delenv("TOOL_OUTPUT_MAX_CHARS", raising=False)
    monkeypatch.delenv("MCP_ENABLED", raising=False)
    monkeypatch.delenv("MCP_SERVERS_JSON", raising=False)
